[package]
name = "grass"
version = "0.8.2"
description = "SASS compiler"
readme = "README.md"
license = "MIT"
categories = ["command-line-utilities", "web-programming"]
keywords = ["scss", "sass", "css", "web"]
repository = "https://github.com/connorskees/grass"
authors = ["ConnorSkees <39542938+ConnorSkees@users.noreply.github.com>"]
edition = "2018"
exclude = ["*.scss", "sass-spec", "tests", "Cargo.lock"]
default-run = "grass"

[[bin]]
name = "grass"
path = "src/main.rs"
required-features = ["commandline"]

[lib]
name = "grass"
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[dependencies]
clap = { version = "2.33.0", optional = true }
num-rational = "0.2.3"
num-bigint = "0.2.6"
num-traits = "0.2.11"
once_cell = "1.3.1"
rand = { version = "0.7.3", optional = true }
codemap = "0.1.3"
peekmore = "0.4.0"
wasm-bindgen = { version = "0.2.60", optional = true }
bimap = "0.4.0"

[features]
default = ["commandline", "random"]
# Option (enabled by default): build a binary using clap
commandline = ["clap"]
# Option: enable nightly-only features (for right now, only the `track_caller` attribute) 
nightly = []
# Option (enabled by default): enable the builtin functions `random([$limit])` and `unique-id()`
random = ["rand"]
# Option: compile to web assembly
wasm = ["wasm-bindgen"]
# Option: enable features that assist in profiling (e.g. inline(never))
profiling = []

[dev-dependencies]
tempfile = "3"
paste = "0.1"

[profile.release]
debug = true
panic = "abort"
