[package]
name = "grass"
version = "0.1.0"
description = "An SCSS compiler in Rust"
readme = "README.md"
license = "MIT OR Apache-2.0"
categories = ["command-line-utilities", "web-programming"]
keywords = ["scss", "sass", "css"]
repository = "https://github.com/connorskees/grass"
authors = ["ConnorSkees <39542938+ConnorSkees@users.noreply.github.com>"]
edition = "2018"

[[bin]]
name = "grass"
path = "src/main.rs"
required-features = ["commandline"]

[lib]
name = "grass"
path = "src/lib.rs"
edition = "2018"

[dependencies]
clap = { version = "2.33.0", optional = true }

[features]
default = ["commandline"]
commandline = ["clap"]

[dev-dependencies]
# test imports
tempfile = "3"
