[package]
name = "grass"
version = "0.1.0"
description = "An SCSS compiler in Rust"
readme = "README.md"
license = "MIT OR Apache-2.0"
categories = ["command-line-utilities", "web-programming"]
keywords = ["scss", "sass", "css"]
repository = "https://github.com/connorskees/grass"
authors = ["ConnorSkees <39542938+ConnorSkees@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
# test imports
tempfile = "3"
