[package]
name = "grass"
version = "0.1.0"
description = "An SCSS compiler in Rust"
readme = "README.md"
license = "MIT"
categories = ["command-line-utilities", "web-programming"]
keywords = ["scss", "sass", "css"]
repository = "https://github.com/connorskees/grass"
authors = ["ConnorSkees <39542938+ConnorSkees@users.noreply.github.com>"]
edition = "2018"
exclude = ["*.scss", "sass-spec", "tests"]

[[bin]]
name = "grass"
path = "src/main.rs"
required-features = ["commandline"]

[lib]
name = "grass"
path = "src/lib.rs"

[dependencies]
clap = { version = "2.33.0", optional = true }
lazy_static = "1.4.0"
num-rational = "0.2.3"
num-bigint = "0.2.6"
num-traits = "0.2.11"

[features]
default = ["commandline"]
commandline = ["clap"]
nightly = []

[dev-dependencies]
# test imports
tempfile = "3"
